# NUMPY

In [224]:
import numpy as np # Import the NumPy library. Use the alias 'np' which is a common convention.

In [225]:
np.__version__ # Check NumPy version using __version__ attribute.

'1.26.4'

In [226]:
import sys #importing system

In [227]:
sys.version #checking sys version

'3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]'

In [228]:
l=[10,20,30,40] #creating a list
l
   

[10, 20, 30, 40]

In [229]:
type(l)

list

In [230]:
arr=np.array(l) #creating list into NumPy Arrays

In [231]:
arr

array([10, 20, 30, 40])

In [232]:
type(arr)

numpy.ndarray

In [233]:
np.arange(10) # Create a range of numbers using np.arange().


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [139]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [140]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [141]:
np.arange(20,8)

array([], dtype=int32)

In [142]:
np.arange(-20,7)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6])

In [143]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [234]:
np.zeros(3) #Return a new array of given shape and type, filled with zeros.

array([0., 0., 0.])

In [145]:
np.zeros(3,dtype=int)  #dtype : data-type, optional
    #The desired data-type for the array, e.g., `numpy.int8`.  Default is`numpy.float64`.

array([0, 0, 0])

In [146]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [235]:
np.zeros((2,2)) #(2,2)-rows and columns

array([[0., 0.],
       [0., 0.]])

In [236]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [149]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [150]:
n=np.zeros((10,3))
n

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [151]:
len(n)

10

In [237]:
n1 = np.ones(3 , dtype=int) #Return a new array of given shape and type, filled with ones.
n1

array([1, 1, 1])

In [238]:
np.ones((10,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [154]:
np.tan(20) 

2.237160944224742

In [155]:
arr

array([10, 20, 30, 40])

In [156]:
type(arr)

numpy.ndarray

# Random Numbers with NumPy

In [239]:
rand(3,2)

NameError: name 'rand' is not defined

In [240]:
random.rand(3,2)

array([[0.51912419, 0.37373926],
       [0.34291085, 0.26903201],
       [0.6534808 , 0.41861762]])

In [242]:
np.random.rand(2) # Generate random floats between 0 and 1 using np.random.rand().

array([0.15699986, 0.58982299])

In [243]:
    np.random.rand(4)

array([0.09482891, 0.68264382, 0.27160063, 0.82921158])

In [244]:
np.random.rand(2,3) # (2,3)-(rows,col)

array([[0.40911961, 0.63312606, 0.00988327],
       [0.51765588, 0.21180011, 0.96662473]])

In [245]:
np.random.randint(3) # Generate random integers in a given range using np.random.randint().

0

In [248]:
np.random.randint(2,20)  #(low, high=None,)-shows range from 2-20

11

In [249]:
np.random.randint(2,10,3) #(2-10)- shows range from 2-10 and generate 3 random numbers

array([3, 6, 2])

In [250]:
np.random.randint(2,20,15)

array([ 8, 12,  2, 18, 15,  6,  7,  4, 17,  9,  3,  3,  5,  8,  9])

In [251]:
np.random.randint(-30,10,17)

array([-15, -17, -16, -20,  -2,   2, -22,   2,  -8, -22,   5, -22,   3,
       -12,  -9,   2, -22])

In [252]:
np.random.randint(10,15,(3,4)) #(10,15)_random numbers range from 10 to 15 and (3-4) are (rows,col)

array([[11, 11, 13, 11],
       [12, 12, 13, 10],
       [12, 10, 14, 12]])

In [253]:
m= np.random.randint(10,100,(3,3))
m

array([[44, 18, 16],
       [41, 99, 94],
       [34, 28, 52]])

In [254]:
arr

array([10, 20, 30, 40])

# Reshaping and Flattening

In [256]:
arr

array([10, 20, 30, 40])

In [257]:
arr.reshape(2,2) #Returns an array containing the same data with a new shape.

array([[10, 20],
       [30, 40]])

In [258]:
l=[2,3,4,5,6,7,8,10,1,1,11,12,13,14,15,16]
l

[2, 3, 4, 5, 6, 7, 8, 10, 1, 1, 11, 12, 13, 14, 15, 16]

In [259]:
arr=np.array(l)
arr

array([ 2,  3,  4,  5,  6,  7,  8, 10,  1,  1, 11, 12, 13, 14, 15, 16])

In [261]:
arr.reshape(4,4)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8, 10],
       [ 1,  1, 11, 12],
       [13, 14, 15, 16]])

In [262]:
m

array([[44, 18, 16],
       [41, 99, 94],
       [34, 28, 52]])

# Array Indexing and Slicing

In [265]:
b=np.random.randint(10,20,(5,4))

In [266]:
b

array([[17, 10, 16, 19],
       [15, 17, 19, 12],
       [16, 14, 16, 14],
       [17, 17, 10, 15],
       [11, 12, 18, 19]])

In [268]:
b[::-1] #reverse order

array([[11, 12, 18, 19],
       [17, 17, 10, 15],
       [16, 14, 16, 14],
       [15, 17, 19, 12],
       [17, 10, 16, 19]])

In [269]:
b[1:4] #print 1st row to 4rd row

array([[15, 17, 19, 12],
       [16, 14, 16, 14],
       [17, 17, 10, 15]])

In [272]:
b[-1:] #print last row

array([[11, 12, 18, 19]])

In [273]:
b

array([[17, 10, 16, 19],
       [15, 17, 19, 12],
       [16, 14, 16, 14],
       [17, 17, 10, 15],
       [11, 12, 18, 19]])

In [274]:
b[:-1] #print all row except last row

array([[17, 10, 16, 19],
       [15, 17, 19, 12],
       [16, 14, 16, 14],
       [17, 17, 10, 15]])

In [275]:
b[:-2] #print all row except last two rows

array([[17, 10, 16, 19],
       [15, 17, 19, 12],
       [16, 14, 16, 14]])

In [276]:
b[1,2] #print 1st row and 2nd column elements

19

In [277]:
b

array([[17, 10, 16, 19],
       [15, 17, 19, 12],
       [16, 14, 16, 14],
       [17, 17, 10, 15],
       [11, 12, 18, 19]])

In [278]:
b[1,2]

19

In [279]:
b[1,3]

12

In [280]:
b

array([[17, 10, 16, 19],
       [15, 17, 19, 12],
       [16, 14, 16, 14],
       [17, 17, 10, 15],
       [11, 12, 18, 19]])

In [281]:
b[1,-1]

12

In [282]:
b[2,-2]

16

## numpy operations

In [301]:
import numpy as np
from numpy import *

In [302]:
arr1 = [1,2,3,4,5]
arr1

[1, 2, 3, 4, 5]

In [303]:
arr2=[5,6,7,8,9]
arr2

[5, 6, 7, 8, 9]

In [304]:
#element-wise addition between two arrays
np.add(arr1,arr2)

array([ 6,  8, 10, 12, 14])

In [318]:
np.subtract(arr1,arr2) #Subtract arguments, element-wise.

array([-4, -4, -4, -4, -4])

In [319]:
np.multiply(arr1,arr2) #Multiply arguments element-wise.


array([ 5, 12, 21, 32, 45])

In [320]:
np.divide(arr1,arr2) #Divide arguments element-wise.


array([0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [308]:
arr1

[1, 2, 3, 4, 5]

In [321]:
mean(arr1) #Compute the arithmetic mean along the specified axis.

3.0

In [310]:
min(arr1) #With a single iterable argument, return its smallest item. The default keyword-only argument specifies an object to return if the provided iterable is empty.

1

In [311]:
max(arr1) #With a single iterable argument, return its biggest item. The default keyword-only argument specifies an object to return if the provided iterable is empty.

5

In [322]:
sum(arr1) #Sum of array elements over a given axis.

15

In [323]:
average(arr1) #Compute the weighted average along the specified axis.


3.0

In [315]:
median(arr1) #Compute the median along the specified axis.

3.0

In [324]:
sqrt(arr1) #Return the non-negative square-root of an array, element-wise.

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [325]:
add(arr1,2) #Add arguments element-wise.

array([3, 4, 5, 6, 7])

# ----------

In [335]:
mat= arange(0,100) #creating a matrix
mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [336]:
matt=mat.reshape(10,10)
matt

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [329]:
row=4
col = 5

In [330]:
col

5

In [331]:
matt[row,col] #to access 4rd row and 5th column

45

In [332]:
matt

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [333]:
matt[1] #access the 2nd row

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [334]:
matt[:,col] #access the 6th column

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [209]:
matt[:,4] #access the 4rd column

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [210]:
matt[:,3] #access the 3rd column

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [211]:
matt

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
matt[::-1] #reverse order

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [213]:
matt[::-2] 

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [214]:
matt

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
matt[2:6,2:3] #gives 2nd to 6th row and 2nd to 3rd column

array([[22],
       [32],
       [42],
       [52]])

In [216]:
matt[2:6,2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [217]:
matt[1:2,2:4]

array([[12, 13]])

In [218]:
matt[3:5,2:4]

array([[32, 33],
       [42, 43]])

## Masking

In [337]:
matt

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [338]:
matt<50 #gives true if elements are are less than 50 or else false

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [221]:
matt>50 #gives true if elements are greater than 50 or else false

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [222]:
matt[matt>50] #it will produce ony those elements which are greater than 50

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [339]:
matt[matt>=50] #similary it will produce those elements which are greater than equal to 50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [340]:
matt[matt<50] #to produce less than 50 elements

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [341]:
matt[matt<=50] #to produce less than and equal to 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])